"""the on-device detector: fit it, prove its C port's algorithm, export it to the board.

the board has never had a model. it streams to the fleet master, the master
scores, and without the master the board shows no verdict at all. that leaves
milestone M2 (the full loop ON the device) open, and it leaves the privacy
claim false: the raw waveform has to leave the board to be judged.

the autoencoder is 4 MB int8 and needs TFLite Micro. the statistical baseline
is ten features and a 10x10 matrix -- 520 bytes of model -- and it runs on the
board in plain C++. the price is measured, not guessed: leave-one-subject-out
on WESAD it scores PR-AUC 0.635 / recall@90spec 0.437 against the deployed
autoencoder's 0.706 / 0.545 (anomaly/RESULTS.md). that gap IS the accuracy cost
of running on-device, which is the number O7 asks for.

what goes on the board, all in sketch_aug3a/:

    board_model.h     GENERATED by this script: the fitted detector, the filter,
                      the runtime constants (mirrored from anomaly.fleet and
                      anomaly.quality), and self-test vectors
    board_detector.h  the algorithm, hand-written C++: quality gate, features,
                      Mahalanobis, the live self-referencing scale

there is no host C compiler on the dev machine, so the port is verified in
three layers:

    1. `--check`: a loop-for-loop Python mirror of every C routine (odd-extended
       zero-phase filtering, scipy's find_peaks semantics, a kiss-style
       mixed-radix FFT, the movement gate) is compared against scipy/numpy and
       anomaly.quality on real WESAD windows. this proves the ALGORITHM.
    2. the header compiles with the ESP32 cross-compiler (see COMMANDS.md).
    3. the board runs the baked self-test vectors through the C++ at boot and
       reports pass/fail on serial and /health. this proves the TRANSLATION.

    python -m anomaly.board_export               # fit + write board_model.h
    python -m anomaly.board_export --check 300   # verify the mirror on 300 windows
"""
from __future__ import annotations

import argparse
import hashlib
import math
import os
import time

import numpy as np

from . import quality
from .baseline import MahalanobisDetector
from .features import FEATURE_NAMES, N_FEATURES, extract_features
from .wesad import FS, WESAD_DIR

HERE = os.path.dirname(os.path.abspath(__file__))
SKETCH = os.path.join(os.path.dirname(HERE), "sketch_aug3a")
OUT = os.path.join(SKETCH, "board_model.h")
CACHE = os.path.join(WESAD_DIR, "_harness_cache", "win60_step5.npz")
WIN = 60 * FS
NORMAL, POSITIVE = 1, 2

# the same filter features._bandpass builds
from scipy.signal import butter, sosfilt_zi  # noqa: E402

SOS = butter(2, [0.7, 3.0], btype="band", fs=FS, output="sos")
ZI = sosfilt_zi(SOS)
PADLEN = 3 * (2 * len(SOS) + 1 - min(int((SOS[:, 2] == 0).sum()), int((SOS[:, 5] == 0).sum())))
_freqs = np.fft.rfftfreq(WIN, 1.0 / FS)
_band = np.flatnonzero((_freqs >= 0.7) & (_freqs <= 3.0))
BAND_LO, BAND_HI = int(_band[0]), int(_band[-1])
NBINS = WIN // 2 + 1
PEAK_DIST = int(FS * 0.4)


# =================================================================== the mirror
#
# every function below is written the way the C++ is: explicit loops, explicit
# indices, no library call whose semantics the C would have to guess. numpy is
# used only where the C does the same arithmetic in a plain loop.

def m_filtfilt(x: np.ndarray) -> np.ndarray:
    """scipy.signal.sosfiltfilt(SOS, x) with its defaults: odd extension by
    PADLEN, sosfilt_zi steady state scaled by the first sample of each pass."""
    n, p = len(x), PADLEN
    ext = np.empty(n + 2 * p)
    for i in range(p):
        ext[i] = 2.0 * x[0] - x[p - i]
    ext[p:p + n] = x
    for j in range(p):
        ext[p + n + j] = 2.0 * x[n - 1] - x[n - 2 - j]

    def run(buf, scale):
        z = ZI * scale
        out = np.empty_like(buf)
        for k in range(len(buf)):
            v = buf[k]
            for s in range(len(SOS)):
                b0, b1, b2, _, a1, a2 = SOS[s]
                y = b0 * v + z[s, 0]
                z[s, 0] = b1 * v - a1 * y + z[s, 1]
                z[s, 1] = b2 * v - a2 * y
                v = y
            out[k] = v
        return out

    y = run(ext, ext[0])
    y = run(y[::-1].copy(), y[-1])
    return y[::-1][p:p + n]


def m_find_peaks(x: np.ndarray, distance: int, prominence) -> list:
    """scipy.signal.find_peaks(x, distance=, prominence=): local maxima (plateaus
    resolved to their midpoint), then distance by descending height, then
    prominence with no window limit."""
    n = len(x)
    peaks = []
    i, i_max = 1, n - 1
    while i < i_max:
        if x[i - 1] < x[i]:
            ahead = i + 1
            while ahead < i_max and x[ahead] == x[i]:
                ahead += 1
            if x[ahead] < x[i]:
                peaks.append((i + ahead - 1) // 2)
                i = ahead
        i += 1
    m = len(peaks)
    keep = [True] * m
    # ascending by height; ties by position (numpy's argsort leaves ties
    # unspecified -- exact float ties between peaks do not occur in practice)
    order = sorted(range(m), key=lambda j: (x[peaks[j]], j))
    for r in range(m - 1, -1, -1):
        j = order[r]
        if not keep[j]:
            continue
        k = j - 1
        while k >= 0 and peaks[j] - peaks[k] < distance:
            keep[k] = False
            k -= 1
        k = j + 1
        while k < m and peaks[k] - peaks[j] < distance:
            keep[k] = False
            k += 1
    peaks = [pk for pk, kp in zip(peaks, keep) if kp]
    if prominence is None:
        return peaks
    out = []
    for pk in peaks:
        h = x[pk]
        lmin, i = h, pk
        while i >= 0 and x[i] <= h:
            if x[i] < lmin:
                lmin = x[i]
            i -= 1
        rmin, i = h, pk
        while i <= n - 1 and x[i] <= h:
            if x[i] < rmin:
                rmin = x[i]
            i += 1
        if h - max(lmin, rmin) >= prominence:
            out.append(pk)
    return out


def _factor(n: int) -> list:
    """kiss_fft's factorisation: 4s first, then 2, then odd primes."""
    out, p = [], 4
    while n > 1:
        while n % p:
            p = 2 if p == 4 else (3 if p == 2 else p + 2)
        n //= p
        out.append((p, n))
    return out


def m_fft(x: np.ndarray) -> np.ndarray:
    """a kiss-style recursive mixed-radix DIT FFT with a generic butterfly --
    the exact recursion board_detector.h uses."""
    N = len(x)
    tw = np.exp(-2j * np.pi * np.arange(N) / N)
    fac = _factor(N)
    out = np.zeros(N, complex)

    def work(fo: int, fi: int, fstride: int, level: int):
        p, m = fac[level]
        if m == 1:
            for q in range(p):
                out[fo + q] = x[fi + q * fstride]
        else:
            for q in range(p):
                work(fo + q * m, fi + q * fstride, fstride * p, level + 1)
        scratch = np.empty(p, complex)
        for u in range(m):
            k = u
            for q1 in range(p):
                scratch[q1] = out[fo + k]
                k += m
            k = u
            for q1 in range(p):
                acc = scratch[0]
                tidx = 0
                for q in range(1, p):
                    tidx += fstride * k
                    if tidx >= N:
                        tidx -= N
                    acc += scratch[q] * tw[tidx]
                out[fo + k] = acc
                k += m

    work(0, 0, 1, 0)
    return out


def m_features(window: np.ndarray, fft=np.fft.rfft) -> np.ndarray:
    """features.extract_features, the way board_detector.h computes it."""
    x = np.asarray(window, dtype=np.float64)
    n = len(x)
    mean = x.sum() / n
    sd = math.sqrt(((x - mean) ** 2).sum() / n)
    x = (x - mean) / (sd + 1e-8)
    f = np.full(N_FEATURES, np.nan)
    bp = m_filtfilt(x)
    bmean = bp.sum() / n
    bsd = math.sqrt(((bp - bmean) ** 2).sum() / n)
    f[4] = bsd
    f[5] = bp.max() - bp.min()
    f[9] = np.abs(np.diff(x)).sum() / (n - 1)
    peaks = m_find_peaks(bp, PEAK_DIST, bsd * 0.3 if bsd > 0 else None)
    if len(peaks) >= 3:
        ibi = np.diff(peaks) / FS
        s = np.sort(ibi)
        k = len(s)
        med = s[k // 2] if k % 2 else 0.5 * (s[k // 2 - 1] + s[k // 2])
        f[0] = 60.0 / med
        im = ibi.sum() / k
        f[1] = math.sqrt(((ibi - im) ** 2).sum() / k)
        d = np.diff(ibi)
        f[2] = math.sqrt((d ** 2).sum() / len(d))
    f[3] = len(peaks) / (n / FS)
    X = fft(x)[:NBINS]
    psd = X.real ** 2 + X.imag ** 2
    tot = psd.sum() + 1e-12
    band = psd[BAND_LO:BAND_HI + 1]
    bs = band.sum()
    f[6] = (BAND_LO + int(np.argmax(band))) * FS / float(n) if bs > 0 else np.nan
    f[7] = bs / tot
    p = psd / tot
    f[8] = -(p * np.log(p + 1e-12)).sum() / math.log(NBINS)
    return f


def m_percentile(a, q: float) -> float:
    """numpy's default (linear) percentile."""
    s = sorted(a)
    pos = (len(s) - 1) * q / 100.0
    lo = int(math.floor(pos))
    hi = min(lo + 1, len(s) - 1)
    return s[lo] + (pos - lo) * (s[hi] - s[lo])


def m_median(a) -> float:
    return m_percentile(a, 50.0)


def m_std(a) -> float:
    a = np.asarray(a, np.float64)
    mu = a.sum() / len(a)
    return math.sqrt(((a - mu) ** 2).sum() / len(a))


def m_artifact_mask(w) -> np.ndarray:
    w = np.asarray(w, np.float64)
    n = len(w)
    d = np.empty(n)
    d[0] = 0.0
    d[1:] = w[1:] - w[:-1]
    med = m_median(d)
    mad = m_median(np.abs(d - med)) * 1.4826
    mask = np.zeros(n, bool)
    if mad < quality.MIN_MAD:
        return mask
    for i in range(n):
        if abs(d[i] - med) > quality.SPIKE_Z * mad:
            lo, hi = max(i - quality.SPREAD, 0), min(i + quality.SPREAD + 1, n)
            mask[lo:hi] = True
    if not mask.any():
        return mask
    # bridge: runs of the mask, and the displaced plateaus between them
    runs, i = [], 0
    while i < n:
        if mask[i]:
            j = i
            while j < n and mask[j]:
                j += 1
            runs.append((i, j))
            i = j
        else:
            i += 1
    if len(runs) < 2:
        return mask
    good = w[~mask]
    if len(good) < 2:
        return mask
    gmed = m_median(good)
    gmad = m_median(np.abs(good - gmed)) * 1.4826
    if gmad < quality.MIN_MAD:
        return mask
    out = mask.copy()
    for (_, end), (start, _) in zip(runs, runs[1:]):
        if start - end <= 0 or start - end > quality.BRIDGE_GAP:
            continue
        if abs(m_median(w[end:start]) - gmed) > quality.BRIDGE_Z * gmad:
            out[end:start] = True
    return out


def m_repair(w, mask) -> np.ndarray:
    w = np.asarray(w, np.float32).copy()
    n = len(w)
    if not mask.any() or (~mask).sum() < 2:
        return w
    i = 0
    while i < n:
        if not mask[i]:
            i += 1
            continue
        j = i
        while j < n and mask[j]:
            j += 1
        a, b = i - 1, j                      # nearest good either side
        for k in range(i, j):
            if a < 0:
                w[k] = w[b]
            elif b >= n:
                w[k] = w[a]
            else:
                w[k] = w[a] + (k - a) * (float(w[b]) - float(w[a])) / (b - a)
        i = j
    return w


def m_clean_window(hist, need: int = WIN, fs: int = FS) -> dict:
    """quality.clean_window, the way board_detector.h does it."""
    hist = np.asarray(hist, np.float32)
    n = max(1, int(fs * quality.ENVELOPE_SEC))
    need_secs = -(-need // n)
    k = len(hist) // n
    out = {"window": None, "dropped": 0, "quality": 0.0, "ok": False, "repaired": 0}
    if k < need_secs:
        return out
    amp = [m_std(hist[i * n:(i + 1) * n]) for i in range(k)]
    ref = m_percentile(amp, quality.ENVELOPE_REF_Q)
    if ref < quality.MIN_MAD:
        return out
    picks = []
    for i in range(k - 1, -1, -1):
        if amp[i] / ref <= quality.ENVELOPE_RATIO:
            picks.append(i)
            if len(picks) == need_secs:
                break
    if len(picks) < need_secs:
        return out
    picks.sort()
    w = np.concatenate([hist[i * n:(i + 1) * n] for i in picks])[:need]
    mask = m_artifact_mask(w)
    bad = mask.sum() / len(w)
    if bad and bad <= quality.MAX_REPAIR:
        w = m_repair(w, mask)
        out["repaired"] = int(mask.sum())
    span = picks[-1] - picks[0] + 1
    out.update(window=w, dropped=span - need_secs, quality=need_secs / span, ok=True)
    return out


# ================================================================== the check

def load_cache():
    if not os.path.exists(CACHE):
        raise SystemExit("no window cache at %s -- run `python -m anomaly.run --model baseline` "
                         "once to build it" % CACHE)
    z = np.load(CACHE)
    subs = sorted({k[:-2] for k in z.files if k.endswith("_X")}, key=lambda s: int(s[1:]))
    return {s: (z[s + "_X"], z[s + "_c"]) for s in subs}


def check(data, n_windows: int, seed: int = 0) -> bool:
    rng = np.random.default_rng(seed)
    pool = [(s, i) for s, (X, c) in data.items() for i in range(len(X))]
    pick = [pool[j] for j in rng.choice(len(pool), size=min(n_windows, len(pool)), replace=False)]
    t0 = time.time()

    # 1. features: mirror (numpy FFT) vs features.extract_features
    err = np.zeros(N_FEATURES)
    nan_mismatch = 0
    for s, i in pick:
        w = data[s][0][i]
        a, b = m_features(w), extract_features(w, FS)
        both = np.isnan(a) & np.isnan(b)
        nan_mismatch += int((np.isnan(a) != np.isnan(b)).sum())
        e = np.where(both, 0.0, np.abs(a - b) / np.maximum(1.0, np.abs(b)))
        err = np.maximum(err, np.nan_to_num(e, nan=np.inf))
    print("  features, mirror vs anomaly.features on %d windows (%.0f s):" % (len(pick), time.time() - t0))
    for name, e in zip(FEATURE_NAMES, err):
        print("    %-17s max rel err %.2e" % (name, e))
    ok = bool(err.max() < 1e-9 and nan_mismatch == 0)
    print("    NaN disagreements: %d   -> %s" % (nan_mismatch, "PASS" if ok else "FAIL"))

    # 2. the FFT recursion vs numpy, on real windows
    fe = 0.0
    for s, i in pick[:3]:
        x = data[s][0][i].astype(np.float64)
        ref = np.fft.fft(x)
        fe = max(fe, float(np.abs(m_fft(x) - ref).max() / np.abs(ref).max()))
    fok = fe < 1e-10
    print("  mixed-radix FFT (factors %s) vs numpy: max rel err %.1e -> %s" % (
        [p for p, _ in _factor(WIN)], fe, "PASS" if fok else "FAIL"))

    # 3. the movement gate vs anomaly.quality on synthetic disturbances
    qok = True
    kinds = {"refused": 0, "whole": 0, "stitched": 0, "repaired": 0}
    for trial in range(40):
        s, i = pick[trial % len(pick)]
        base = np.concatenate([data[s][0][i], data[s][0][(i + 12) % len(data[s][0])]])[:150 * FS]
        hist = base.astype(np.float32).copy()
        r2 = np.random.default_rng(trial)
        for _ in range(int(r2.integers(0, 4))):           # bursts of movement
            a = int(r2.integers(0, len(hist) - 6 * FS))
            hist[a:a + int(r2.integers(1, 6)) * FS] *= float(r2.uniform(2, 8))
        # sample-level knocks, sized on the spike test's own scale (the robust
        # spread of sample-to-sample steps): big enough to be caught, small
        # enough that their second survives the envelope and gets REPAIRED
        d = np.diff(base.astype(np.float64))
        step = float(np.median(np.abs(d - np.median(d))) * 1.4826)
        for _ in range(int(r2.integers(1, 4))):
            a = int(r2.integers(1, len(hist) - 3))
            hist[a] += float(r2.uniform(80, 150)) * step
        want = quality.clean_window(hist, WIN, FS)
        got = m_clean_window(hist, WIN, FS)
        if want["window"] is None:
            kinds["refused"] += 1
        else:
            kinds["stitched" if want["dropped"] else "whole"] += 1
        kinds["repaired"] += int(got["repaired"] > 0)
        same = (want["window"] is None) == (not got["ok"])
        if same and got["ok"]:
            same = (want["dropped"] == got["dropped"] and
                    np.allclose(want["window"], got["window"], rtol=0, atol=1e-5))
        qok &= bool(same)
    # every path has to have been exercised, or a PASS says nothing about it
    qok &= kinds["refused"] > 0 and kinds["stitched"] > 0 and kinds["repaired"] > 0
    print("  movement gate vs anomaly.quality on 40 disturbed histories %s -> %s" % (
        kinds, "PASS" if qok else "FAIL"))
    return ok and fok and qok


# ================================================================= the export

def _c(v: float) -> str:
    if v is None or (isinstance(v, float) and math.isnan(v)) or (hasattr(v, "dtype") and np.isnan(v)):
        return "NAN"
    t = "%.9g" % float(v)
    if not any(ch in t for ch in ".en"):     # "15f" is not a C literal; "15.f" is
        t += "."
    return t + "f"


def _cd(v: float) -> str:
    t = "%.17g" % float(v)
    return t if any(ch in t for ch in ".en") else t + ".0"


def _arr(vals, per=8, fmt=_c) -> str:
    vals = [fmt(v) for v in vals]
    return ",\n    ".join(", ".join(vals[i:i + per]) for i in range(0, len(vals), per))


def export(data, out: str = OUT) -> dict:
    from . import fleet

    calm = np.concatenate([X[c == NORMAL] for X, c in data.values()])
    print("  fitting on %d calm windows from %d WESAD subjects…" % (len(calm), len(data)))
    t0 = time.time()
    F = np.array([extract_features(w, FS) for w in calm], dtype=np.float32)
    det = MahalanobisDetector().fit_features(F)
    print("  features in %.0f s" % (time.time() - t0))

    def score(w):
        f = np.array([extract_features(w, FS)], dtype=np.float32)
        return float(np.sqrt(max(float(det.score_features(f)[0]), 0.0)))

    # self-test windows: one calm and one stress, plus a movement history built
    # from the calm one that the gate must STITCH and REPAIR. WESAD wrist BVP is
    # noisy enough that many calm windows break the device-tuned envelope on
    # their own, so the calm window is searched for rather than hard-coded.
    def gate_history(w):
        # BD_TEST_X[0] twice (120 s), seconds 70-74 at 6x amplitude, one knock
        # at 5000 of 100 step-sigmas: caught by the spike test (60), small
        # enough that its second survives the envelope and gets repaired
        h = np.concatenate([w, w]).astype(np.float32)
        h[70 * FS:75 * FS] *= np.float32(6.0)
        d = np.diff(w.astype(np.float64))
        kn = np.float32(100.0 * np.median(np.abs(d - np.median(d))) * 1.4826)
        h[5000] += kn
        return h, kn

    X, c = data["S5"]
    calm_idx, stress_idx = np.flatnonzero(c == NORMAL), np.flatnonzero(c == POSITIVE)
    for j in calm_idx:
        hist, knock = gate_history(X[j])
        r = m_clean_window(hist, WIN, FS)
        if r["ok"] and r["dropped"] and r["repaired"]:
            break
    else:
        raise SystemExit("no S5 calm window both stitches and repairs; widen the search")
    gate = quality.clean_window(hist, WIN, FS)
    assert gate["window"] is not None and gate["dropped"] == r["dropped"]
    tests = [X[j], X[stress_idx[len(stress_idx) // 2]]]
    tf = [extract_features(w, FS) for w in tests]
    ts = [score(w) for w in tests]
    gw = gate["window"].astype(np.float64)
    gate_sum, gate_sq = float(gw.sum()), float((gw * gw).sum())

    params = np.concatenate([det.median_, det.mu_, det.sd_, det.center_, det.inv_cov_.ravel()])
    tag = "maha-wesad%d-%s" % (len(data), hashlib.sha256(params.astype(np.float32).tobytes()).hexdigest()[:10])

    L = []
    w = L.append
    w("// GENERATED by `python -m anomaly.board_export` -- do not edit by hand.")
    w("// the on-device detector: Mahalanobis on %d features, fitted on %d calm" % (N_FEATURES, len(calm)))
    w("// WESAD windows from %d subjects. LOSO on WESAD: PR-AUC 0.635 / recall@90spec" % len(data))
    w("// 0.437, against the host autoencoder's 0.706 / 0.545 -- the on-device cost.")
    w("// the algorithm lives in board_detector.h; this file is only numbers.")
    w("#pragma once")
    w("#include <math.h>")
    w("")
    w('#define BD_MODEL_TAG "%s"' % tag)
    w("#define BD_FS %d" % FS)
    w("#define BD_WIN %d                 // 60 s at 64 Hz: the window the model scores" % WIN)
    w("#define BD_HIST %d                // 150 s: slack to drop movement and back-fill" % fleet.HIST)
    w("#define BD_NF %d" % N_FEATURES)
    w("#define BD_NBINS %d" % NBINS)
    w("#define BD_BAND_LO %d             // rfft bins 0.7..3.0 Hz, inclusive" % BAND_LO)
    w("#define BD_BAND_HI %d" % BAND_HI)
    w("#define BD_PEAK_DIST %d           // find_peaks distance, samples" % PEAK_DIST)
    w("#define BD_PADLEN %d              // sosfiltfilt odd-extension length" % PADLEN)
    w("")
    w("// butter(2, [0.7, 3.0], btype='band', fs=64) and its sosfilt_zi, in double:")
    w("// the zero-phase pass runs in double so a near-tie peak cannot flip on rounding")
    w("static const double BD_SOS[2][6] = {")
    for r in SOS:
        w("  {%s}," % ", ".join(_cd(v) for v in r))
    w("};")
    w("static const double BD_ZI[2][2] = {")
    for r in ZI:
        w("  {%s}," % ", ".join(_cd(v) for v in r))
    w("};")
    w("")
    w("// the fitted detector (anomaly.baseline.MahalanobisDetector)")
    w("// features: " + ", ".join(FEATURE_NAMES))
    for name, arr in (("BD_MEDIAN", det.median_), ("BD_MU", det.mu_),
                      ("BD_SD", det.sd_), ("BD_CENTER", det.center_)):
        w("static const float %s[BD_NF] = {\n    %s};" % (name, _arr(arr, per=5)))
    w("static const float BD_INVCOV[BD_NF][BD_NF] = {")
    for r in det.inv_cov_:
        w("  {%s}," % ", ".join(_c(v) for v in r))
    w("};")
    w("")
    w("// the live scale, mirrored from anomaly/fleet.py defaults. the master's")
    w("// roster can retune these at runtime; the board uses what was exported.")
    w("#define BD_EMA_ALPHA %sf" % fleet.EMA_ALPHA)
    w("#define BD_NORM_N %d" % fleet.NORM_N)
    w("#define BD_NORM_MIN %d" % fleet.NORM_MIN)
    w("#define BD_NORM_Q %sf" % float(fleet.NORM_Q))
    w("#define BD_SPREAD_FLOOR %sf" % fleet.SPREAD_FLOOR)
    w("#define BD_Z_FULL %sf" % fleet.Z_FULL)
    w("#define BD_FLAG_ON_S %d" % fleet.FLAG_ON_S)
    w("#define BD_FLAG_OFF_S %d" % fleet.FLAG_OFF_S)
    w("#define BD_THR_MIN %sf" % fleet.THR_MIN)
    w("#define BD_THR_MAX %sf" % fleet.THR_MAX)
    w("")
    w("// the movement gate, mirrored from anomaly/quality.py")
    w("#define BD_SPIKE_Z %sf" % quality.SPIKE_Z)
    w("#define BD_SPREAD %d" % quality.SPREAD)
    w("#define BD_BRIDGE_GAP %d" % quality.BRIDGE_GAP)
    w("#define BD_BRIDGE_Z %sf" % quality.BRIDGE_Z)
    w("#define BD_MAX_REPAIR %sf" % quality.MAX_REPAIR)
    w("#define BD_MIN_MAD %gf" % quality.MIN_MAD)
    w("#define BD_ENVELOPE_RATIO %sf" % quality.ENVELOPE_RATIO)
    w("#define BD_ENVELOPE_REF_Q %sf" % float(quality.ENVELOPE_REF_Q))
    w("")
    w("// self-test: the C++ must reproduce these, computed by the Python reference")
    w("#define BD_NTEST 2")
    w("static const float BD_TEST_X[BD_NTEST][BD_WIN] = {")
    for t in tests:
        w("  {%s}," % _arr(t, per=10))
    w("};")
    w("static const float BD_TEST_F[BD_NTEST][BD_NF] = {")
    for f in tf:
        w("  {%s}," % ", ".join(_c(v) for v in f))
    w("};")
    w("static const float BD_TEST_SCORE[BD_NTEST] = {%s};" % ", ".join(_c(v) for v in ts))
    w("// gate test: BD_TEST_X[0] twice, s70-74 x6, BD_GATE_KNOCK added at sample 5000;")
    w("// the gate must stitch out the burst (dropped seconds) and repair the knock")
    w("#define BD_GATE_KNOCK_AT 5000")
    w("#define BD_GATE_KNOCK %s" % _c(knock))
    w("#define BD_GATE_DROPPED %d" % gate["dropped"])
    w("#define BD_GATE_SUM %s" % _cd(gate_sum))
    w("#define BD_GATE_SUMSQ %s" % _cd(gate_sq))
    w("")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w", encoding="ascii", newline="\n") as fh:
        fh.write("\n".join(L))
    kb = os.path.getsize(out) / 1024.0
    print("  wrote %s (%.0f KB, tag %s)" % (out, kb, tag))
    print("  self-test scores: calm %.3f, stress %.3f; gate dropped %d s" % (ts[0], ts[1], gate["dropped"]))
    return {"tag": tag, "scores": ts}


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", type=int, metavar="N",
                    help="verify the C mirror against scipy/numpy/quality on N windows")
    ap.add_argument("--out", default=OUT)
    a = ap.parse_args(argv)
    data = load_cache()
    if a.check:
        return 0 if check(data, a.check) else 1
    export(data, a.out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
