"""bake the dashboard into a C header the ESP32 serves straight from flash.

run from the repo root:

    python3 sketch_aug3a/make_web_assets.py

writes sketch_aug3a/web_assets.h -- gzipped copies of the dashboard files as
PROGMEM arrays, served with Content-Encoding: gzip.

why embed rather than use LittleFS: no filesystem partition, no upload plugin,
and the assets can never drift out of sync with the firmware that serves them.
they are ~65 KB gzipped, which is nothing against 16 MB of flash.
"""
from __future__ import annotations

import gzip
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

# (route, source file, mime type, C identifier)
ASSETS = [
    ("/",                 "pulse/Pulse Watch.dc.html",      "text/html",              "watch_html"),
    ("/support.js",       "pulse/support.js",               "application/javascript", "support_js"),
    ("/dev",              "anomaly/static/index.html",      "text/html",              "dev_html"),
    ("/vendor/uPlot.iife.min.js",
     "pipeline/static/vendor/uPlot.iife.min.js", "application/javascript", "uplot_js"),
    ("/vendor/uPlot.min.css",
     "pipeline/static/vendor/uPlot.min.css",     "text/css",               "uplot_css"),
]


def c_array(name: str, blob: bytes) -> str:
    out = [f"const uint8_t {name}[] PROGMEM = {{"]
    for i in range(0, len(blob), 16):
        row = ", ".join(f"0x{b:02x}" for b in blob[i:i + 16])
        out.append("  " + row + ",")
    out.append("};")
    out.append(f"const size_t {name}_len = {len(blob)};")
    return "\n".join(out)


def main() -> int:
    parts, table, total_raw, total_gz = [], [], 0, 0

    for route, rel, mime, ident in ASSETS:
        path = os.path.join(ROOT, rel)
        if not os.path.exists(path):
            print(f"  MISSING: {rel}")
            return 1
        raw = open(path, "rb").read()
        gz = gzip.compress(raw, 9)
        total_raw += len(raw)
        total_gz += len(gz)
        print(f"  {route:28s} {len(raw):>7,} -> {len(gz):>6,} B gzip   {rel}")
        parts.append(c_array(ident, gz))
        table.append(f'  {{ "{route}", {ident}, {ident}_len, "{mime}" }},')

    header = f'''// GENERATED by sketch_aug3a/make_web_assets.py -- do not edit by hand.
// Re-run that script after changing anything in pulse/ or anomaly/static/.
//
// {total_raw:,} bytes of dashboard, {total_gz:,} bytes gzipped.
#pragma once

#include <Arduino.h>
#include <pgmspace.h>

{chr(10).join(parts)}

struct WebAsset {{
  const char *route;
  const uint8_t *data;
  size_t len;
  const char *mime;
}};

const WebAsset WEB_ASSETS[] = {{
{chr(10).join(table)}
}};
const size_t WEB_ASSET_COUNT = sizeof(WEB_ASSETS) / sizeof(WEB_ASSETS[0]);
'''

    out = os.path.join(HERE, "web_assets.h")
    open(out, "w", encoding="utf-8", newline="\n").write(header)
    print(f"\n  wrote {out}")
    print(f"  {total_raw:,} B raw -> {total_gz:,} B in flash "
          f"({100 * total_gz / total_raw:.0f}%)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
